#!/usr/bin/env python3
import os
import sys
import subprocess

data_dir = './storage/data'
db_json_file = './storage/data/.verdaccio-db.json'

# must start this script with sudoer
if os.geteuid() != 0:
    print("You need to have root privileges to run this script.")
    sys.exit(1)

# build .verdaccio-db.json file
result = []

for root, dirs, files in os.walk("./storage/data"):
    for dir in dirs:
        result.append('"' + dir + '"')

new_db_json = '{"list":['

new_db_json = new_db_json + ','.join(result) + '],"secret":"849cfbddc086052d06044fef518c1e8669b794f9278365eaf34e7999718e5efd"}'

# open a file in write mode
with open(db_json_file, "w") as file:
    # write string to the file
    file.write(new_db_json)

# start docker-compose

commands = [
    "docker-compose down -v",
    "docker-compose -p verdaccio up -d",
]

for command in commands:
    subprocess.call(command, shell=True)


print('verdaccio started!')
sys.exit(0)

